version: '3'

services:
  sqlserver_npsapp:
    container_name: sqlserver_npsapp
    image: mcr.microsoft.com/mssql/server
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1q2w3e4r@#$
    volumes:
      - npsapp_sqlserver_data:/mcr.microsoft.com/mssql/server

  sonarqube:
    container_name: sonarqube_npsapp
    image: sonarqube:latest
    ports:
      - '9000:9000'
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

volumes:
  npsapp_sqlserver_data:
