version: '3'

services:
  sqlserver_npsapp:
    container_name: sqlserver_npsapp
    image: mcr.microsoft.com/mssql/server
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1q2w3e4r@#$
    volumes:
      - npsapp_sqlserver_data:/mcr.microsoft.com/mssql/server

  redis_npsapp:
    container_name: redis_npsapp
    image: redis
    ports:
      - '6379:6379'

volumes:
  npsapp_sqlserver_data:
